Repository Financial-Times/create-origami-component, pull requests merged in 2020-07, with the labels that each got.

#114 Use the primary mixin in demo scss over silent mode
  templates/demos-scss.js
Labels: release:patch

#117 Only add the project board action when the `origami-core` team are Gi…
  src/tasks/build.js
  templates/helpers/list.js
  test/integration/commands/init.test.js
Labels: release:patch

#118 fix: remember edited answers from cli prompt
  src/prompts/boilerplate.js
  test/unit/prompts/boilerplate.test.js
Labels: release:patch

#119 Add origami.json
  origami.json
Labels: release:patch

#122 Add remark lint config and the missing linting tools themselves for editor plugins to use
  templates/package-json.js
Labels: cli, release:patch

#123 Remove underscore and extension from the brand import
  templates/main-scss.js
Labels: cli, release:patch

#125 build(deps): npm audit fix
  package-lock.json
Labels: cli

#128 Add missing JSDoc @returns for getDataAttributes method
  templates/src-js.js
Labels: cli, release:patch

#127 Make the jsdoc for constructor valid by making the argument name match the given jsdoc name
  templates/src-js.js
Labels: cli, release:patch

#129 Make init method have valid jsdoc
  templates/src-js.js
Labels: cli, release:patch
