Repository Financial-Times/create-origami-component, pull requests merged in 2020-08, with the labels that each got.

#161 Add general usage information to readme boilerplate
  templates/readme.js
Labels: cli, release:patch

#185 Remove commented out config for npm-audit workflow
  .github/workflows/npm-audit-fix.yml
Labels: cli, release:minor

#186 test on node 14 also
  .github/workflows/npm-test.yml
Labels: cli
