Repository Financial-Times/create-origami-component, pull requests merged in 2021-04, with the labels that each got.

#252 build(deps): npm audit fix
  package-lock.json
Labels: cli, dependencies, security

#256 build(deps): npm audit fix
  package-lock.json
Labels: cli, dependencies, security

#257 build(deps): npm audit fix
  package-lock.json
Labels: cli, dependencies, security

#263 run npm-test workflow on all branches and pull-requests
  .github/workflows/npm-test.yml
Labels: cli

#262 Drop "module" type for "component" for spec v2 components
  templates/origami-manifest.js
Labels: cli, release:patch

#264 Remove "origamiCategory" from boilerplate.
  src/prompts/boilerplate.js
  src/prompts/questions.js
  templates/origami-manifest.js
  test/integration/commands/init.test.js
Labels: cli, release:beta
